Importing all the necessary libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from keras.models import Sequential
from keras.layers import Dense

Importing the dataset

In [2]:
columns = ['Class','AGE','SEX','STEROID','ANTIVIRALS','FATIGUE','MALAISE','ANOREXIA','LIVER BIG','LIVER FIRM','SPLEEN PALPABLE','SPIDERS','ASCITES','VARICES','BILIRUBIN','ALK PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']
pd = pd.read_csv(r"C:\Users\priyank\Downloads\hepatitis.data", sep=',', names=columns, na_values='?', header=None)
pd.head

<bound method NDFrame.head of      Class  AGE  SEX  STEROID  ANTIVIRALS  FATIGUE  MALAISE  ANOREXIA  \
0        2   30    2      1.0           2      2.0      2.0       2.0
1        2   50    1      1.0           2      1.0      2.0       2.0
2        2   78    1      2.0           2      1.0      2.0       2.0
3        2   31    1      NaN           1      2.0      2.0       2.0
4        2   34    1      2.0           2      2.0      2.0       2.0
..     ...  ...  ...      ...         ...      ...      ...       ...
150      1   46    1      2.0           2      1.0      1.0       1.0
151      2   44    1      2.0           2      1.0      2.0       2.0
152      2   61    1      1.0           2      1.0      1.0       2.0
153      2   53    2      1.0           2      1.0      2.0       2.0
154      1   43    1      2.0           2      1.0      2.0       2.0

     LIVER BIG  LIVER FIRM  SPLEEN PALPABLE  SPIDERS  ASCITES  VARICES  \
0          1.0         2.0              2.0      2.0      2.0      2.0
1          1.0         2.0              2.0      2.0      2.0      2.0
2          2.0         2.0              2.0      2.0      2.0      2.0
3          2.0         2.0              2.0      2.0      2.0      2.0
4          2.0         2.0              2.0      2.0      2.0      2.0
..         ...         ...              ...      ...      ...      ...
150        2.0         2.0              2.0      1.0      1.0      1.0
151        2.0         1.0              2.0      2.0      2.0      2.0
152        1.0         1.0              2.0      1.0      2.0      2.0
153        2.0         2.0              1.0      1.0      2.0      1.0
154        2.0         2.0              1.0      1.0      1.0      2.0

     BILIRUBIN  ALK PHOSPHATE   SGOT  ALBUMIN  PROTIME  HISTOLOGY
0          1.0           85.0   18.0      4.0      NaN          1
1          0.9          135.0   42.0      3.5      NaN          1
2          0.7           96.0   32.0      4.0      NaN          1
3          0.7           46.0   52.0      4.0     80.0          1
4          1.0            NaN  200.0      4.0      NaN          1
..         ...            ...    ...      ...      ...        ...
150        7.6            NaN  242.0      3.3     50.0          2
151        0.9          126.0  142.0      4.3      NaN          2
152        0.8           75.0   20.0      4.1      NaN          2
153        1.5           81.0   19.0      4.1     48.0          2
154        1.2          100.0   19.0      3.1     42.0          2

[155 rows x 20 columns]>

Filling up the null values with means

In [3]:
pd.fillna(pd.mean(numeric_only=True).round(1), inplace=True)
pd.head(10)

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1.0,2,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,85.0,18.0,4.0,61.9,1
1,2,50,1,1.0,2,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,0.9,135.0,42.0,3.5,61.9,1
2,2,78,1,2.0,2,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,96.0,32.0,4.0,61.9,1
3,2,31,1,1.5,1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.7,46.0,52.0,4.0,80.0,1
4,2,34,1,2.0,2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,105.3,200.0,4.0,61.9,1
5,2,34,1,2.0,2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.9,95.0,28.0,4.0,75.0,1
6,1,51,1,1.0,2,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.4,105.3,85.9,3.8,61.9,1
7,2,23,1,2.0,2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,105.3,85.9,3.8,61.9,1
8,2,39,1,2.0,2,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,0.7,105.3,48.0,4.4,61.9,1
9,2,30,1,2.0,2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,105.3,120.0,3.9,61.9,1

Splitting the data into train and test data

In [4]:
Y = pd['Class']
X = pd.loc[:, pd.columns != 'Class']

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

[[-8.94191753e-01  2.94745653e+00 -1.01627171e+00 ...  3.00133849e-01
   1.58109393e-03 -9.07485213e-01]
 [ 7.02579235e-01 -3.39275572e-01 -1.01627171e+00 ... -5.13165917e-01
   1.58109393e-03 -9.07485213e-01]
 [ 2.93805862e+00 -3.39275572e-01  9.90379433e-01 ...  3.00133849e-01
   1.58109393e-03 -9.07485213e-01]
 ...
 [ 1.58080328e+00 -3.39275572e-01 -1.01627171e+00 ...  4.62793802e-01
   1.58109393e-03  1.10194633e+00]
 [ 9.42094883e-01  2.94745653e+00 -1.01627171e+00 ...  4.62793802e-01
  -8.09482447e-01  1.10194633e+00]
 [ 1.43709389e-01 -3.39275572e-01  9.90379433e-01 ... -1.16380573e+00
  -1.15958182e+00  1.10194633e+00]]

In [6]:
Y = np.asarray(Y).astype('float32')
X = np.asarray(X).astype('float32')
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
Y_train = np.asarray(Y_train).reshape(-1,1)

Creating the model

In [7]:
model = Sequential()
model.add(Dense(19, input_dim=19, activation='sigmoid'))
model.add(Dense(30, activation='sigmoid'))
model.add(Dense(15, activation='sigmoid'))
model.add(Dense(1, activation=None))

Compiling the model

In [8]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=10)

In [9]:
model.fit(X_train, Y_train, epochs=100, batch_size=32, verbose=0)
loss, acc = model.evaluate(X_test, Y_test, verbose=0)
print('Test Accuracy: %.3f' % acc)

Test Accuracy: 0.226

In [10]:
Y_pred = model.predict(X_test)
Y_pred = (Y_pred > 0.5)
print("Accuracy:", accuracy_score(Y_test, Y_pred))

1/1 [==============================] - 0s 101ms/step
Accuracy: 0.22580645161290322